services:
  db:
    image: postgres:13
    env_file: 
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask-api:
    build: .
    env_file: 
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"

volumes:
  postgres_data:
